<?php

return [

    'name' => env('APP_NAME', 'Laravel'),
    'env' => env('APP_ENV', 'production'),
    'debug' => true, //env('APP_DEBUG', false),
    'debug_blacklist' =>[
        '_ENV' => [
            'APP_NAME',
            'APP_ENV',
            'APP_KEY',
            'APP_DEBUG',
            'APP_URL',
            'SESSION_DOMAIN',
            'LOG_CHANNEL',
            'DB_CONNECTION',
            'DB_HOST',
            'DB_PORT',
            'DB_DATABASE',
            'DB_USERNAME',
            'DB_PASSWORD',
            'BROADCAST_DRIVER',
            'CACHE_DRIVER',
            'SESSION_DRIVER',
            'SESSION_LIFETIME',
            'QUEUE_DRIVER',
            'REDIS_HOST',
            'REDIS_PASSWORD',
            'REDIS_PORT',
            'MAIL_DRIVER',
            'MAIL_HOST',
            'MAIL_PORT',
            'MAIL_USERNAME',
            'MAIL_PASSWORD',
            'MAIL_ENCRYPTION',
            'PUSHER_APP_ID',
            'PUSHER_APP_KEY',
            'PUSHER_APP_SECRET',
            'PUSHER_APP_CLUSTER',
            'MIX_PUSHER_APP_KEY',
            'MIX_PUSHER_APP_CLUSTER',
            'REDIRECT_RDS_USERNAME',
            'REDIRECT_RDS_DB_NAME',
            'REDIRECT_RDS_HOSTNAME',
            'REDIRECT_RDS_PASSWORD',
            'REDIRECT_RDS_USERNAME',
            'RDS_HOSTNAME',
            'RDS_USERNAME',
            'RDS_DB_NAME',
            'RDS_PASSWORD',
            'PHP_DOCUMENT_ROOT',
            'REDIRECT_PHP_DOCUMENT_ROOT',
        ],
        '_SERVER' => [
            'TZ',
            'REDIRECT_REDIRECT_UNIQUE_ID',
            'REDIRECT_REDIRECT_SCRIPT_URL',
            'REDIRECT_REDIRECT_SCRIPT_URI',
            'REDIRECT_REDIRECT_HTTPS',
            'REDIRECT_REDIRECT_SSL_TLS_SNI',
            'REDIRECT_REDIRECT_STATUS',
            'REDIRECT_UNIQUE_ID',
            'REDIRECT_SCRIPT_URL',
            'REDIRECT_SCRIPT_URI',
            'REDIRECT_HTTPS',
            'REDIRECT_SSL_TLS_SNI',
            'REDIRECT_HANDLER',
            'REDIRECT_STATUS',
            'UNIQUE_ID',
            'SCRIPT_URL',
            'SCRIPT_URI',
            'HTTPS',
            'SSL_TLS_SNI',
            'HTTP_HOST',
            'HTTP_CONNECTION',
            'HTTP_PRAGMA',
            'HTTP_CACHE_CONTROL',
            'HTTP_UPGRADE_INSECURE_REQUESTS',
            'HTTP_USER_AGENT',
            'HTTP_ACCEPT',
            'HTTP_ACCEPT_ENCODING',
            'HTTP_ACCEPT_LANGUAGE',
            'HTTP_COOKIE',
            'HTTP_X_HTTPS',
            'PATH',
            'SERVER_SIGNATURE',
            'SERVER_SOFTWARE',
            'SERVER_NAME',
            'SERVER_ADDR',
            'SERVER_PORT',
            'REMOTE_ADDR',
            'DOCUMENT_ROOT',
            'CONTEXT_PREFIX',
            'CONTEXT_DOCUMENT_ROOT',
            'SERVER_ADMIN',
            'SCRIPT_FILENAME',
            'REMOTE_PORT',
            'REDIRECT_URL',
            'GATEWAY_INTERFACE',
            'SERVER_PROTOCOL',
            'REQUEST_METHOD',
            'QUERY_STRING',
            'REQUEST_URI',
            'SCRIPT_NAME',
            'ORIG_SCRIPT_FILENAME',
            'ORIG_PATH_INFO',
            'ORIG_PATH_TRANSLATED',
            'ORIG_SCRIPT_NAME',
            'PHP_SELF',
            'REQUEST_TIME_FLOAT',
            'REQUEST_TIME',
            'arg',
            'argc',
            'APP_NAME',
            'APP_ENV',
            'APP_KEY',
            'APP_DEBUG',
            'APP_URL',
            'SESSION_DOMAIN',
            'LOG_CHANNEL',
            'DB_CONNECTION',
            'DB_HOST',
            'DB_PORT',
            'DB_DATABASE',
            'DB_USERNAME',
            'DB_PASSWORD',
            'BROADCAST_DRIVER',
            'CACHE_DRIVER',
            'SESSION_DRIVER',
            'SESSION_LIFETIME',
            'QUEUE_DRIVER',
            'REDIS_HOST',
            'REDIS_PASSWORD',
            'REDIS_PORT',
            'MAIL_DRIVER',
            'MAIL_HOST',
            'MAIL_PORT',
            'MAIL_USERNAME',
            'MAIL_PASSWORD',
            'MAIL_ENCRYPTION',
            'PUSHER_APP_ID',
            'PUSHER_APP_KEY',
            'PUSHER_APP_SECRET',
            'PUSHER_APP_CLUSTER',
            'MIX_PUSHER_APP_CLUSTER',
            'REDIRECT_RDS_USERNAME',
            'REDIRECT_RDS_DB_NAME',
            'REDIRECT_RDS_HOSTNAME',
            'REDIRECT_RDS_PASSWORD',
            'REDIRECT_RDS_USERNAME',
            'RDS_HOSTNAME',
            'RDS_USERNAME',
            'RDS_DB_NAME',
            'RDS_PASSWORD',
            'PHP_DOCUMENT_ROOT',
            'USER',
            'REDIRECT_PHP_DOCUMENT_ROOT',
        ],
        '_POST' => [
            'password',
        ],
    ],
    'url' => env('APP_URL', 'http://localhost'),
    'timezone' => 'UTC',
    'locale' => 'en',
    'fallback_locale' => 'en',
    'key' => env('APP_KEY'),
    'cipher' => 'AES-256-CBC',
    'providers' => [

        /*
         * Laravel Framework Service Providers...
         */
        Illuminate\Auth\AuthServiceProvider::class,
        Illuminate\Broadcasting\BroadcastServiceProvider::class,
        Illuminate\Bus\BusServiceProvider::class,
        Illuminate\Cache\CacheServiceProvider::class,
        Illuminate\Foundation\Providers\ConsoleSupportServiceProvider::class,
        Illuminate\Cookie\CookieServiceProvider::class,
        Illuminate\Database\DatabaseServiceProvider::class,
        Illuminate\Encryption\EncryptionServiceProvider::class,
        Illuminate\Filesystem\FilesystemServiceProvider::class,
        Illuminate\Foundation\Providers\FoundationServiceProvider::class,
        Illuminate\Hashing\HashServiceProvider::class,
        Illuminate\Mail\MailServiceProvider::class,
        Illuminate\Notifications\NotificationServiceProvider::class,
        Illuminate\Pagination\PaginationServiceProvider::class,
        Illuminate\Pipeline\PipelineServiceProvider::class,
        Illuminate\Queue\QueueServiceProvider::class,
        Illuminate\Redis\RedisServiceProvider::class,
        Illuminate\Auth\Passwords\PasswordResetServiceProvider::class,
        Illuminate\Session\SessionServiceProvider::class,
        Illuminate\Translation\TranslationServiceProvider::class,
        Illuminate\Validation\ValidationServiceProvider::class,
        Illuminate\View\ViewServiceProvider::class,
        LaravelQRCode\Providers\QRCodeServiceProvider::class,

        /*
         * Package Service Providers...
         */

        /*
         * Application Service Providers...
         */
        App\Providers\AppServiceProvider::class,
        App\Providers\AuthServiceProvider::class,
        // App\Providers\BroadcastServiceProvider::class,
        App\Providers\EventServiceProvider::class,
        App\Providers\RouteServiceProvider::class,
        Intervention\Image\ImageServiceProvider::class,
        SimpleSoftwareIO\QrCode\QrCodeServiceProvider::class

    ],
    'aliases' => [

        'App' => Illuminate\Support\Facades\App::class,
        'Artisan' => Illuminate\Support\Facades\Artisan::class,
        'Auth' => Illuminate\Support\Facades\Auth::class,
        'Blade' => Illuminate\Support\Facades\Blade::class,
        'Broadcast' => Illuminate\Support\Facades\Broadcast::class,
        'Bus' => Illuminate\Support\Facades\Bus::class,
        'Cache' => Illuminate\Support\Facades\Cache::class,
        'Config' => Illuminate\Support\Facades\Config::class,
        'Cookie' => Illuminate\Support\Facades\Cookie::class,
        'Crypt' => Illuminate\Support\Facades\Crypt::class,
        'DB' => Illuminate\Support\Facades\DB::class,
        'Eloquent' => Illuminate\Database\Eloquent\Model::class,
        'Event' => Illuminate\Support\Facades\Event::class,
        'File' => Illuminate\Support\Facades\File::class,
        'Gate' => Illuminate\Support\Facades\Gate::class,
        'Hash' => Illuminate\Support\Facades\Hash::class,
        'Lang' => Illuminate\Support\Facades\Lang::class,
        'Log' => Illuminate\Support\Facades\Log::class,
        'Mail' => Illuminate\Support\Facades\Mail::class,
        'Notification' => Illuminate\Support\Facades\Notification::class,
        'Password' => Illuminate\Support\Facades\Password::class,
        'Queue' => Illuminate\Support\Facades\Queue::class,
        'Redirect' => Illuminate\Support\Facades\Redirect::class,
        'Redis' => Illuminate\Support\Facades\Redis::class,
        'Request' => Illuminate\Support\Facades\Request::class,
        'Response' => Illuminate\Support\Facades\Response::class,
        'Route' => Illuminate\Support\Facades\Route::class,
        'Schema' => Illuminate\Support\Facades\Schema::class,
        'Session' => Illuminate\Support\Facades\Session::class,
        'Storage' => Illuminate\Support\Facades\Storage::class,
        'URL' => Illuminate\Support\Facades\URL::class,
        'Validator' => Illuminate\Support\Facades\Validator::class,
        'View' => Illuminate\Support\Facades\View::class,
        'Image' => Intervention\Image\Facades\Image::class,
        'QRCode' => LaravelQRCode\Facades\QRCode::class,
        'QR' => SimpleSoftwareIO\QrCode\Facades\QrCode::class
    ],

];